ITEM_ID_FIELD: track
MAX_ITEM_LIST_LENGTH: 50
TIME_FIELD: timestamp
USER_ID_FIELD: user
encoding: utf-8
epochs: 5
eval_args:
  group_by: user
  mode: full
  order: TO
  split:
    RS:
    - 9
    - 1
    - 0
eval_batch_size: 4096
field_separator: "\t"
item_inter_num_interval: '[3,inf)'
load_col:
  inter:
  - timestamp
  - user
  - track
  - time
  item:
  - artist
  - album
  - title
  - genre
  - pop
  - track
loss_type: CE
numerical_features:
- pop
seed: 1488
seq_separator: ' '
train_batch_size: 2048
train_neg_sample_args: null
user_inter_num_interval: '[3,inf)'
